SPW 3652 handle redirect
showpass/showpass-wordpress-plugin pull request #26
Opened 2020-12-10 22:41 UTC by marc-thomas

Handles the redirect to the third party external_link if the website has an access key and the event has an external_link present

2020-12-11 01:10 UTC, april-duong requested changes

2020-12-11 01:10 UTC, april-duong commented on plugin/js/showpass-custom.js
> +                        .then(response => response.json())
You don't need `then` if you're awaiting. Can probably just do:
```
try {
    const response = await fetch('https://www.showpass.com/api/public/events/' + slug + '/')
    if (response) {
        const data = await response.json();
        if (data) {
            if (data.id && data.external_link) {
                window.location.href = data.external_link;
            } else {
                openWidget();
            }
        }
        return data;
    }
    return response;
} catch (() => {
    openWidget();
});
```

2020-12-11 01:10 UTC, april-duong commented on plugin/showpass-wordpress-custom-api.php
> +    $showpassEvent = strpos($validURL, 'showpass.com');
Same issue here that I left in PR #25

2020-12-14 20:09 UTC, jaredrooprai approved these changes

2020-12-14 20:25 UTC, april-duong approved these changes

2020-12-14 20:46 UTC, merged