refactor: add tags to old calendar widget
showpass/showpass-wordpress-plugin pull request #30
Opened 2021-05-20 22:06 UTC by davidma415

Adding tags (similar to embed calendar widget)

2021-05-20 22:36 UTC, jaredrooprai approved these changes

2021-05-21 20:05 UTC, april-duong requested changes
Looks good, just minor indent issues

2021-05-21 20:05 UTC, april-duong commented on plugin/showpass-wordpress-plugin-shortcode.php
> +  : null;
minor: indentation

2021-05-21 20:05 UTC, april-duong commented on plugin/js/showpass-custom.js
> +                'tags': $(this).attr('data-tags')
not sure if it's github doing this but the indent is misaligned

2021-05-21 20:31 UTC, davidma415 commented
@april-duong  weird indentations, but fixed them. should be good now.

2021-05-21 21:49 UTC, april-duong approved these changes

2021-05-25 15:24 UTC, merged